name: yemen_laws_app
description: Yemen Law - Offline legal reference app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.0
  shared_preferences: ^2.3.0
  connectivity_plus: ^6.0.0
  share_plus: ^10.0.0
  fluttertoast: ^8.2.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
